name: Generate LetsEncrypt Certificate
on: 
  workflow_dispatch:
jobs:
  certbot:
    strategy:
      matrix:
        domain: [dianhsu.com, cdn.dianhsu.com]
    name: certbot
    runs-on: ubuntu-latest
    steps:
    - name: Generate LetsEncrypt Cert
      uses: shibme/cloudflare-letsencrypt-certbot-generate@main
      with:
        cloudflare_dns_api_token: ${{ secrets.CLOUDFLARE_DNS_API_TOKEN }}
        domain_name: ${{ matrix.domain }}
        email: ${{ secrets.NOTIFY_EMAIL }}
        certs_file_name: ${{ matrix.domain }}
        dry_run: false
    - name: Upload to Qiniu
      run: |
        unzip ${{ matrix.domain }}.zip
        ls -al

    - name: update qiniu ${{ matrix.domain }}
      uses: foxundermoon/upload-qiniu-cert-action@master
      with:
        ak: ${{ secrets.QINIU_AK }}
        sk: ${{ secrets.QINIU_SK }}
        domain: ${{ matrix.domain }}
        update-domains: |
          .${{ matrix.domain }} | https | http2
          ${{ matrix.domain }} | https | http2
        debug: 'yes'
        cert-path: 'fullchain1.pem'
        key-path: 'privkey1.pem'
